import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'

class Home extends React.Component {

  constructor(props: any) {
    super(props);

    this.state = { todoItems: [] };
    this.createTodoItem = this.createTodoItem.bind(this);
  }

  createTodoItem(e: any) {
    e.preventDefault();
    console.log('You clicked.')

    const formData = new FormData(e.target);
    const formProps = Object.fromEntries(formData);
    console.log(formProps)

    const taskName = formProps.taskName;
    const dueDate = formProps.dueDate;
    console.log({ taskName, dueDate })

    const todoItem = { taskName, dueDate }

    this.setState({
      // @ts-ignore
      todoItems: [...this.state.todoItems, todoItem]
    })
  }




  render() {
    return <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Todo List App
      </h1>

      <form onSubmit={this.createTodoItem}>
        <label htmlFor="taskName">Task</label>
        <input type="text" id="taskName" name="taskName" />


        <label htmlFor="dueDate">Due Date</label>
        <input type="date" id="dueDate" name="dueDate" />


        <button type="submit">Create</button>


      </form>


      <div className={styles.grid}>

      </div>
    </div>
  }
}

export default Home
